environment:
  P: "c:/projects/libs"

branches:
  only:
    - appveyor-prep
    
version: 0.11.{build}

image:
- Visual Studio 2019

init:
  - git config --global core.autocrlf input
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
  - echo %generator%
  - set zip_name=SDL_gpu_%version%-%configuration%-VC-%platform%.zip


shallow_clone: true
clone_folder: c:\projects\SDL_gpu

install:
  - mkdir c:\projects\libs
  # Download SDL.
  - ps: Start-FileDownload 'https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip' 'c:/projects/libs/SDL.zip'
  
  # Extract it, put it in the right place, and rename it.
  - cd c:\projects\libs && 7z x SDL.zip && ren SDL2-2.0.12 SDL2 && cd c:\projects\SDL_gpu


platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

# scripts to run before build
before_build:
  - echo "Platform %platform%"
  - echo "generator %generator%"
  - echo Running cmake...
  - cd c:\projects\SDL_gpu
  - mkdir build
  - cd build
  - if "%configuration%"=="Debug" ( set build_tests=ON )
  - if "%configuration%"=="Debug" ( set build_demos=OFF )
  - if "%configuration%"=="Release" ( set build_tests=OFF )
  - if "%configuration%"=="Release" ( set build_demos=ON )
  - cmd: cmake -G %generator% -A %platform% -DCMAKE_INSTALL_PREFIX=c:\projects\libs\SDL2 -DSDL_gpu_BUILD_DEMOS=%build_demos% -DSDL_gpu_BUILD_TESTS=%build_tests% -DSDL_gpu_BUILD_TOOLS=%build_demos% -DSDL_gpu_BUILD_SHARED=ON -DSDL_gpu_BUILD_STATIC=ON ..

# scripts to run after build
after_build:
  - cd c:\projects\SDL_gpu\build
  - 7z a c:\projects\SDL_gpu\%zip_name% * -tzip
  - cd c:\projects\SDL_gpu

artifacts:
  - path: "%zip_name%"
    name: "%zip_name%"

deploy_script:
  - cd c:\projects\SDL_gpu
#  - curl -T SDL_gpu.zip --user %ACCOUNT% https://www.dinomage.com/SDL_gpu.zip