environment:
  P: "c:/projects/libs"

branches:
  only:
    - appveyor-prep
    
version: 0.11.{build}

image:
- Visual Studio 2019
- Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - echo %generator%


shallow_clone: true
clone_folder: c:\projects\SDL_gpu

install:
  - mkdir c:\projects\libs
  # Download SDL.
  - ps: Start-FileDownload 'https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip' 'c:/projects/libs/SDL.zip'
  
  # Extract it, put it in the right place, and rename it.
  - cd c:\projects\libs && 7z x SDL.zip && ren SDL2-2.0.5 SDL2 && cd c:\projects\SDL_gpu


platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

# scripts to run before build
before_build:
  - echo "Platform: %platform%"
  - echo "generator: %generator%"
  - echo Running cmake...
  - cd c:\projects\SDL_gpu
  - mkdir build
  - cd build
  - cmd: cmake -G %generator% -A %platform% -DCMAKE_INSTALL_PREFIX=c:\projects\libs\SDL2 -DSDL_gpu_BUILD_DEMOS=ON -DSDL_gpu_BUILD_TESTS=ON -DSDL_gpu_BUILD_TOOLS=ON -DSDL_gpu_BUILD_SHARED=ON -DSDL_gpu_BUILD_STATIC=ON ..

# scripts to run after build
after_build:
  - cd c:\projects\SDL_gpu\build
  - 7z a c:\projects\SDL_gpu\SDL_gpu.zip * -tzip
  - cd c:\projects\SDL_gpu

artifacts:
  - path: SDL_gpu.zip
    name: SDL_gpu.zip

deploy_script:
  - cd c:\projects\SDL_gpu
#  - curl -T SDL_gpu.zip --user %ACCOUNT% https://www.dinomage.com/SDL_gpu.zip